server:
  port:9192
 #jdbc properties (for mysql)
spring:
  datasource:
     driver-class-name:com.mysql.cj.jdbc.Driver
     url=jdbc:mysql:///NTSPBMS616DB
     username=root
     password=root
  
  #Hibernate specific JPA Properties
  jpa:
    datasource-platform:org.hibernate.dialect.MySQL8Dilect
    show-sql:true
    hibernate.ddl-auto:update